[W 2025-10-09 20:00:09.668 ServerApp] ServerApp.password config is deprecated in 2.0. Use PasswordIdentityProvider.hashed_password.
[I 2025-10-09 20:00:09.754 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2025-10-09 20:00:09.759 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2025-10-09 20:00:09.764 ServerApp] jupyterlab | extension was successfully linked.
[I 2025-10-09 20:00:09.769 ServerApp] nbclassic | extension was successfully linked.
[I 2025-10-09 20:00:10.443 ServerApp] notebook_shim | extension was successfully linked.
[I 2025-10-09 20:00:10.506 ServerApp] notebook_shim | extension was successfully loaded.
[I 2025-10-09 20:00:10.509 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2025-10-09 20:00:10.511 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2025-10-09 20:00:10.519 LabApp] JupyterLab extension loaded from /home/kayvans/.local/lib/python3.10/site-packages/jupyterlab
[I 2025-10-09 20:00:10.519 LabApp] JupyterLab application directory is /home/kayvans/.local/share/jupyter/lab
[I 2025-10-09 20:00:10.520 LabApp] Extension Manager is 'pypi'.
[I 2025-10-09 20:00:10.805 ServerApp] jupyterlab | extension was successfully loaded.
[I 2025-10-09 20:00:10.817 ServerApp] nbclassic | extension was successfully loaded.
[I 2025-10-09 20:00:10.818 ServerApp] Serving notebooks from local directory: /home/kayvans/mimic-demo
[I 2025-10-09 20:00:10.818 ServerApp] Jupyter Server 2.16.0 is running at:
[I 2025-10-09 20:00:10.818 ServerApp] http://cs320:2020/lab
[I 2025-10-09 20:00:10.818 ServerApp]     http://127.0.0.1:2020/lab
[I 2025-10-09 20:00:10.818 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 2025-10-09 20:00:10.847 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-language-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
[W 2025-10-09 20:00:16.325 LabApp] Could not determine jupyterlab build status without nodejs
[W 2025-10-09 20:00:16.508 ServerApp] 404 GET /api/contents/starter_patient.ipynb?content=0&hash=0&1760040016475 (b961125cf2e042caa8b8251d01f89643@72.33.2.215) 1.64ms referer=http://34.61.98.138:2020/lab/tree/projects/mp3/mp3.ipynb
[W 2025-10-09 20:00:16.508 ServerApp] 404 GET /api/contents/starter_patient.ipynb?content=0&hash=0&1760040016475 (72.33.2.215): No such file or directory: starter_patient.ipynb
[W 2025-10-09 20:00:16.511 ServerApp] 404 GET /api/contents/starter_patient.ipynb?content=0&hash=0&1760040016474 (b961125cf2e042caa8b8251d01f89643@72.33.2.215) 0.94ms referer=http://34.61.98.138:2020/lab/tree/projects/mp3/mp3.ipynb
[W 2025-10-09 20:00:16.511 ServerApp] 404 GET /api/contents/starter_patient.ipynb?content=0&hash=0&1760040016474 (72.33.2.215): No such file or directory: starter_patient.ipynb
[W 2025-10-09 20:00:17.666 ServerApp] 404 GET /api/contents/projects/mp3/mp3.ipynb?content=0&hash=0&1760040017648 (b961125cf2e042caa8b8251d01f89643@72.33.2.215) 1.34ms referer=http://34.61.98.138:2020/lab/tree/projects/mp3/mp3.ipynb
[W 2025-10-09 20:00:17.666 ServerApp] 404 GET /api/contents/projects/mp3/mp3.ipynb?content=0&hash=0&1760040017648 (72.33.2.215): No such file or directory: projects/mp3/mp3.ipynb
[I 2025-10-09 20:00:28.933 ServerApp] 302 GET / (@72.33.2.215) 0.63ms
[W 2025-10-09 20:00:30.089 LabApp] Could not determine jupyterlab build status without nodejs
[I 2025-10-09 20:00:35.821 ServerApp] Kernel started: e39584db-3cc4-4010-9171-e429ce6c7d01
[I 2025-10-09 20:00:36.642 ServerApp] Connecting to kernel e39584db-3cc4-4010-9171-e429ce6c7d01.
[I 2025-10-09 20:00:36.646 ServerApp] Connecting to kernel e39584db-3cc4-4010-9171-e429ce6c7d01.
[I 2025-10-09 20:00:36.651 ServerApp] Connecting to kernel e39584db-3cc4-4010-9171-e429ce6c7d01.
[W 2025-10-09 20:00:36.655 ServerApp] The websocket_ping_timeout (90000) cannot be longer than the websocket_ping_interval (30000).
    Setting websocket_ping_timeout=30000
[W 2025-10-09 20:00:36.819 ServerApp] Got events for closed stream <zmq.eventloop.zmqstream.ZMQStream object at 0x797bb0734d90>
[I 2025-10-09 20:01:20.458 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-09 20:01:24.126 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-09 20:02:10.665 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-09 20:02:10.976 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-09 20:02:11.656 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-09 20:02:11.853 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-09 20:02:15.829 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[W 2025-10-09 20:02:17.758 ServerApp] 404 GET /api/contents/data/mimic-iv-clinical-database-demo-2.2/hosp/icustays.csv.gz?content=0&hash=0&1760040137721 (b961125cf2e042caa8b8251d01f89643@72.33.2.215) 1.37ms referer=http://34.61.98.138:2020/lab/tree/notebooks/starter_patient.ipynb
[W 2025-10-09 20:02:17.759 ServerApp] 404 GET /api/contents/data/mimic-iv-clinical-database-demo-2.2/hosp/icustays.csv.gz?content=0&hash=0&1760040137721 (72.33.2.215): No such file or directory: data/mimic-iv-clinical-database-demo-2.2/hosp/icustays.csv.gz
[I 2025-10-09 20:02:24.940 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-09 20:03:04.967 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-09 20:03:38.021 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-09 20:03:51.940 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-09 20:03:56.637 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-09 20:03:58.958 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-09 20:04:13.111 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-09 20:04:14.877 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-09 20:06:15.002 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-09 20:07:58.539 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-09 20:08:14.798 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-09 20:08:26.981 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-09 20:10:02.160 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-09 20:10:36.743 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-09 20:11:13.442 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-09 20:11:22.485 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-09 20:11:23.428 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-09 20:11:49.370 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-09 20:13:49.482 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-09 20:13:51.326 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-09 20:13:54.925 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-09 20:15:12.798 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-09 20:17:12.980 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-09 20:24:01.562 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-09 20:24:05.380 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[W 2025-10-09 20:31:06.647 ServerApp] WebSocket ping timeout after 119903 ms.
[I 2025-10-09 20:31:11.652 ServerApp] Starting buffering for e39584db-3cc4-4010-9171-e429ce6c7d01:a5ed49e4-9882-46a6-ab36-6cc4ebb4c1fa
[I 2025-10-09 20:45:22.670 ServerApp] Connecting to kernel e39584db-3cc4-4010-9171-e429ce6c7d01.
[I 2025-10-09 20:45:22.671 ServerApp] Restoring connection for e39584db-3cc4-4010-9171-e429ce6c7d01:a5ed49e4-9882-46a6-ab36-6cc4ebb4c1fa
[I 2025-10-09 20:46:53.914 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-09 20:46:58.370 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-09 20:47:23.294 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-09 20:47:45.888 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-09 20:47:51.850 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-09 20:47:56.565 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-09 20:48:06.230 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-09 20:48:22.624 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-09 20:49:14.417 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-09 20:49:32.410 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-09 20:51:32.612 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-09 20:51:47.830 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-09 20:51:58.454 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-09 20:53:08.357 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-09 20:53:09.400 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-09 20:55:08.468 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-09 20:55:41.543 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-09 20:56:29.314 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-09 20:57:42.448 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-09 20:58:58.514 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-09 21:00:53.324 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-09 21:02:46.272 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-09 21:03:15.993 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-09 21:03:16.296 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-09 21:03:16.621 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-09 21:04:23.896 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-09 21:04:52.086 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-09 21:05:54.351 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-09 21:06:12.766 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-09 21:06:25.600 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-09 21:06:34.317 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-09 21:08:28.690 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-09 21:09:46.245 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-09 21:10:40.535 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-09 21:12:40.670 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-09 21:14:40.800 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-09 21:16:24.061 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-09 21:18:24.171 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-09 21:22:42.668 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-09 21:23:26.682 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-09 21:25:26.830 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-09 21:27:00.081 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-09 21:29:01.688 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-09 21:37:29.547 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-09 21:42:14.553 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-09 21:43:24.669 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-09 21:44:03.736 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-09 21:44:10.657 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-09 21:45:30.999 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-09 21:45:46.475 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-09 21:47:46.764 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-09 21:55:06.934 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-09 21:55:10.238 ServerApp] Kernel shutdown: e39584db-3cc4-4010-9171-e429ce6c7d01
[I 2025-10-09 21:55:12.585 ServerApp] Shutting down on /api/shutdown request.
[I 2025-10-09 21:55:12.586 ServerApp] Shutting down 5 extensions

  _   _          _      _
 | | | |_ __  __| |__ _| |_ ___
 | |_| | '_ \/ _` / _` |  _/ -_)
  \___/| .__/\__,_\__,_|\__\___|
       |_|

Read the migration plan to Notebook 7 to learn about the new features and the actions to take if you are using extensions.

https://jupyter-notebook.readthedocs.io/en/latest/migrate_to_notebook7.html

Please note that updating to Notebook 7 might break some of your extensions.

[W 2025-10-10 18:17:21.304 ServerApp] ServerApp.password config is deprecated in 2.0. Use PasswordIdentityProvider.hashed_password.
[I 2025-10-10 18:17:21.398 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2025-10-10 18:17:21.403 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2025-10-10 18:17:21.409 ServerApp] jupyterlab | extension was successfully linked.
[I 2025-10-10 18:17:21.414 ServerApp] nbclassic | extension was successfully linked.
[I 2025-10-10 18:17:22.114 ServerApp] notebook_shim | extension was successfully linked.
[I 2025-10-10 18:17:22.177 ServerApp] notebook_shim | extension was successfully loaded.
[I 2025-10-10 18:17:22.180 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2025-10-10 18:17:22.181 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2025-10-10 18:17:22.189 LabApp] JupyterLab extension loaded from /home/kayvans/.local/lib/python3.10/site-packages/jupyterlab
[I 2025-10-10 18:17:22.189 LabApp] JupyterLab application directory is /home/kayvans/.local/share/jupyter/lab
[I 2025-10-10 18:17:22.190 LabApp] Extension Manager is 'pypi'.
[I 2025-10-10 18:17:22.472 ServerApp] jupyterlab | extension was successfully loaded.
[I 2025-10-10 18:17:22.484 ServerApp] nbclassic | extension was successfully loaded.
[I 2025-10-10 18:17:22.485 ServerApp] Serving notebooks from local directory: /home/kayvans/mimic-demo
[I 2025-10-10 18:17:22.485 ServerApp] Jupyter Server 2.16.0 is running at:
[I 2025-10-10 18:17:22.485 ServerApp] http://cs320:2020/lab
[I 2025-10-10 18:17:22.485 ServerApp]     http://127.0.0.1:2020/lab
[I 2025-10-10 18:17:22.485 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 2025-10-10 18:17:22.514 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-language-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
[W 2025-10-10 18:17:26.554 LabApp] Could not determine jupyterlab build status without nodejs
[I 2025-10-10 18:17:27.683 ServerApp] Kernel started: 67fcf8b0-63a4-46ed-9cde-97e93829238b
[I 2025-10-10 18:17:28.714 ServerApp] Connecting to kernel 67fcf8b0-63a4-46ed-9cde-97e93829238b.
[I 2025-10-10 18:17:28.719 ServerApp] Connecting to kernel 67fcf8b0-63a4-46ed-9cde-97e93829238b.
[I 2025-10-10 18:17:28.724 ServerApp] Connecting to kernel 67fcf8b0-63a4-46ed-9cde-97e93829238b.
[W 2025-10-10 18:17:28.727 ServerApp] The websocket_ping_timeout (90000) cannot be longer than the websocket_ping_interval (30000).
    Setting websocket_ping_timeout=30000
[I 2025-10-10 18:18:08.386 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-10 18:18:08.768 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-10 18:18:09.122 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-10 18:18:47.574 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-10 18:20:06.448 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-10 18:20:13.037 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-10 18:20:56.439 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-10 18:22:21.073 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-10 18:23:50.198 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-10 18:24:08.444 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-10 18:26:08.744 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-10 18:27:48.488 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-10 18:29:31.892 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-10 18:29:38.678 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-10 18:31:39.023 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-10 18:32:42.831 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-10 18:32:49.142 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-10 18:32:51.362 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-10 18:40:49.656 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-10 18:41:06.391 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-10 18:42:05.301 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-10 18:42:21.910 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-10 18:44:02.175 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-10 18:44:09.115 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-10 18:46:02.454 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-10 18:46:36.402 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-10 18:48:36.733 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-10 18:50:37.126 ServerApp] Saving file at /notebooks/starter_patient.ipynb
[I 2025-10-10 18:53:22.291 ServerApp] Kernel shutdown: 67fcf8b0-63a4-46ed-9cde-97e93829238b
[I 2025-10-10 18:53:24.688 ServerApp] Shutting down on /api/shutdown request.
[I 2025-10-10 18:53:24.689 ServerApp] Shutting down 5 extensions

  _   _          _      _
 | | | |_ __  __| |__ _| |_ ___
 | |_| | '_ \/ _` / _` |  _/ -_)
  \___/| .__/\__,_\__,_|\__\___|
       |_|

Read the migration plan to Notebook 7 to learn about the new features and the actions to take if you are using extensions.

https://jupyter-notebook.readthedocs.io/en/latest/migrate_to_notebook7.html

Please note that updating to Notebook 7 might break some of your extensions.

[W 2025-10-16 19:38:37.732 ServerApp] ServerApp.password config is deprecated in 2.0. Use PasswordIdentityProvider.hashed_password.
[I 2025-10-16 19:38:37.828 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2025-10-16 19:38:37.834 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2025-10-16 19:38:37.840 ServerApp] jupyterlab | extension was successfully linked.
[I 2025-10-16 19:38:37.844 ServerApp] nbclassic | extension was successfully linked.
[I 2025-10-16 19:38:38.545 ServerApp] notebook_shim | extension was successfully linked.
[I 2025-10-16 19:38:38.614 ServerApp] notebook_shim | extension was successfully loaded.
[I 2025-10-16 19:38:38.617 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2025-10-16 19:38:38.618 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2025-10-16 19:38:38.626 LabApp] JupyterLab extension loaded from /home/kayvans/.local/lib/python3.10/site-packages/jupyterlab
[I 2025-10-16 19:38:38.627 LabApp] JupyterLab application directory is /home/kayvans/.local/share/jupyter/lab
[I 2025-10-16 19:38:38.627 LabApp] Extension Manager is 'pypi'.
[I 2025-10-16 19:38:38.927 ServerApp] jupyterlab | extension was successfully loaded.
[I 2025-10-16 19:38:38.941 ServerApp] nbclassic | extension was successfully loaded.
[I 2025-10-16 19:38:38.942 ServerApp] Serving notebooks from local directory: /home/kayvans/mimic-demo
[I 2025-10-16 19:38:38.942 ServerApp] Jupyter Server 2.16.0 is running at:
[I 2025-10-16 19:38:38.942 ServerApp] http://cs320:2020/lab
[I 2025-10-16 19:38:38.942 ServerApp]     http://127.0.0.1:2020/lab
[I 2025-10-16 19:38:38.942 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 2025-10-16 19:38:38.975 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-language-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
[I 2025-10-16 19:38:45.259 ServerApp] 302 GET / (@72.33.2.45) 0.73ms
[W 2025-10-16 19:38:45.947 LabApp] Could not determine jupyterlab build status without nodejs
[W 2025-10-16 19:38:46.093 ServerApp] 404 GET /api/contents/Current_Location.jpg?content=0&hash=0&1760643526021 (b961125cf2e042caa8b8251d01f89643@72.33.2.45) 1.61ms referer=http://34.61.98.138:2020/lab?
[W 2025-10-16 19:38:46.093 ServerApp] 404 GET /api/contents/Current_Location.jpg?content=0&hash=0&1760643526021 (72.33.2.45): No such file or directory: Current_Location.jpg
[W 2025-10-16 19:38:46.093 ServerApp] 404 GET /api/contents/test.ipynb?content=0&hash=0&1760643526021 (b961125cf2e042caa8b8251d01f89643@72.33.2.45) 2.21ms referer=http://34.61.98.138:2020/lab?
[W 2025-10-16 19:38:46.094 ServerApp] 404 GET /api/contents/test.ipynb?content=0&hash=0&1760643526021 (72.33.2.45): No such file or directory: test.ipynb
[W 2025-10-16 19:38:46.094 ServerApp] 404 GET /api/contents/Untitled.ipynb?content=0&hash=0&1760643526021 (b961125cf2e042caa8b8251d01f89643@72.33.2.45) 2.60ms referer=http://34.61.98.138:2020/lab?
[W 2025-10-16 19:38:46.094 ServerApp] 404 GET /api/contents/Untitled.ipynb?content=0&hash=0&1760643526021 (72.33.2.45): No such file or directory: Untitled.ipynb
[W 2025-10-16 19:38:46.096 ServerApp] 404 GET /api/contents/Current_Location.jpg?content=0&hash=0&1760643526021 (b961125cf2e042caa8b8251d01f89643@72.33.2.45) 1.10ms referer=http://34.61.98.138:2020/lab?
[W 2025-10-16 19:38:46.096 ServerApp] 404 GET /api/contents/Current_Location.jpg?content=0&hash=0&1760643526021 (72.33.2.45): No such file or directory: Current_Location.jpg
[W 2025-10-16 19:38:46.096 ServerApp] 404 GET /api/contents/scrape.py?content=0&hash=0&1760643526021 (b961125cf2e042caa8b8251d01f89643@72.33.2.45) 1.42ms referer=http://34.61.98.138:2020/lab?
[W 2025-10-16 19:38:46.096 ServerApp] 404 GET /api/contents/scrape.py?content=0&hash=0&1760643526021 (72.33.2.45): No such file or directory: scrape.py
[W 2025-10-16 19:38:46.113 ServerApp] 404 GET /api/contents/test.ipynb?content=0&hash=0&1760643526021 (b961125cf2e042caa8b8251d01f89643@72.33.2.45) 1.16ms referer=http://34.61.98.138:2020/lab?
[W 2025-10-16 19:38:46.113 ServerApp] 404 GET /api/contents/test.ipynb?content=0&hash=0&1760643526021 (72.33.2.45): No such file or directory: test.ipynb
[W 2025-10-16 19:38:46.115 ServerApp] 404 GET /api/contents/scrape.py?content=0&hash=0&1760643526021 (b961125cf2e042caa8b8251d01f89643@72.33.2.45) 1.13ms referer=http://34.61.98.138:2020/lab?
[W 2025-10-16 19:38:46.115 ServerApp] 404 GET /api/contents/scrape.py?content=0&hash=0&1760643526021 (72.33.2.45): No such file or directory: scrape.py
[I 2025-10-16 19:38:52.400 ServerApp] Kernel started: 4339458d-8a1a-455e-abcd-5f26e4607d25
[I 2025-10-16 19:38:53.421 ServerApp] Connecting to kernel 4339458d-8a1a-455e-abcd-5f26e4607d25.
[I 2025-10-16 19:38:53.426 ServerApp] Connecting to kernel 4339458d-8a1a-455e-abcd-5f26e4607d25.
[I 2025-10-16 19:38:53.431 ServerApp] Connecting to kernel 4339458d-8a1a-455e-abcd-5f26e4607d25.
[W 2025-10-16 19:38:53.435 ServerApp] The websocket_ping_timeout (90000) cannot be longer than the websocket_ping_interval (30000).
    Setting websocket_ping_timeout=30000
[I 2025-10-16 19:39:51.490 ServerApp] Creating new notebook in /notebooks
[I 2025-10-16 19:39:51.708 ServerApp] Kernel started: e15b07c7-4596-4a7e-9995-cc622a6d2916
[I 2025-10-16 19:39:52.431 ServerApp] Connecting to kernel e15b07c7-4596-4a7e-9995-cc622a6d2916.
[I 2025-10-16 19:42:40.934 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-16 19:44:41.040 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-16 19:45:20.345 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-16 19:46:51.410 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-16 19:48:32.004 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-16 19:48:34.480 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-16 19:50:36.393 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-16 19:52:36.512 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-16 19:53:09.316 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-16 19:53:34.323 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-16 19:54:58.702 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-16 19:56:58.801 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-16 19:58:58.915 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-16 19:59:30.802 ServerApp] Creating new file in /notebooks
[I 2025-10-16 20:00:45.667 ServerApp] Saving file at /notebooks/untitled.py
[E 2025-10-16 20:00:45.755 ServerApp] Uncaught exception POST /api/contents/notebooks/untitled.py/checkpoints?1760644845709 (72.33.2.45)
    HTTPServerRequest(protocol='http', host='34.61.98.138:2020', method='POST', uri='/api/contents/notebooks/untitled.py/checkpoints?1760644845709', version='HTTP/1.1', remote_ip='72.33.2.45')
    Traceback (most recent call last):
      File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/web.py", line 1848, in _execute
        result = await result
      File "/home/kayvans/.local/lib/python3.10/site-packages/jupyter_server/auth/decorator.py", line 73, in inner
        return await out
      File "/home/kayvans/.local/lib/python3.10/site-packages/jupyter_server/services/contents/handlers.py", line 358, in post
        checkpoint = await ensure_async(cm.create_checkpoint(path))
      File "/home/kayvans/.local/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 197, in ensure_async
        result = await obj
      File "/home/kayvans/.local/lib/python3.10/site-packages/jupyter_server/services/contents/manager.py", line 1083, in create_checkpoint
        return await self.checkpoints.create_checkpoint(self, path)
      File "/home/kayvans/.local/lib/python3.10/site-packages/jupyter_server/services/contents/filecheckpoints.py", line 145, in create_checkpoint
        await self._copy(src_path, dest_path)
      File "/home/kayvans/.local/lib/python3.10/site-packages/jupyter_server/services/contents/fileio.py", line 470, in _copy
        await async_copy2_safe(src, dest, log=self.log)
      File "/home/kayvans/.local/lib/python3.10/site-packages/jupyter_server/services/contents/fileio.py", line 66, in async_copy2_safe
        await run_sync(shutil.copyfile, src, dst)
      File "/home/kayvans/.local/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
        return await get_async_backend().run_sync_in_worker_thread(
      File "/home/kayvans/.local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2470, in run_sync_in_worker_thread
        return await future
      File "/home/kayvans/.local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 967, in run
        result = context.run(func, *args)
      File "/usr/lib/python3.10/shutil.py", line 254, in copyfile
        with open(src, 'rb') as fsrc:
    FileNotFoundError: [Errno 2] No such file or directory: '/home/kayvans/mimic-demo/notebooks/untitled.py'
[W 2025-10-16 20:00:45.770 ServerApp] wrote error: 'Unhandled error'
    Traceback (most recent call last):
      File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/web.py", line 1848, in _execute
        result = await result
      File "/home/kayvans/.local/lib/python3.10/site-packages/jupyter_server/auth/decorator.py", line 73, in inner
        return await out
      File "/home/kayvans/.local/lib/python3.10/site-packages/jupyter_server/services/contents/handlers.py", line 358, in post
        checkpoint = await ensure_async(cm.create_checkpoint(path))
      File "/home/kayvans/.local/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 197, in ensure_async
        result = await obj
      File "/home/kayvans/.local/lib/python3.10/site-packages/jupyter_server/services/contents/manager.py", line 1083, in create_checkpoint
        return await self.checkpoints.create_checkpoint(self, path)
      File "/home/kayvans/.local/lib/python3.10/site-packages/jupyter_server/services/contents/filecheckpoints.py", line 145, in create_checkpoint
        await self._copy(src_path, dest_path)
      File "/home/kayvans/.local/lib/python3.10/site-packages/jupyter_server/services/contents/fileio.py", line 470, in _copy
        await async_copy2_safe(src, dest, log=self.log)
      File "/home/kayvans/.local/lib/python3.10/site-packages/jupyter_server/services/contents/fileio.py", line 66, in async_copy2_safe
        await run_sync(shutil.copyfile, src, dst)
      File "/home/kayvans/.local/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
        return await get_async_backend().run_sync_in_worker_thread(
      File "/home/kayvans/.local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2470, in run_sync_in_worker_thread
        return await future
      File "/home/kayvans/.local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 967, in run
        result = context.run(func, *args)
      File "/usr/lib/python3.10/shutil.py", line 254, in copyfile
        with open(src, 'rb') as fsrc:
    FileNotFoundError: [Errno 2] No such file or directory: '/home/kayvans/mimic-demo/notebooks/untitled.py'
[E 2025-10-16 20:00:45.771 ServerApp] {
      "Host": "34.61.98.138:2020",
      "Accept": "*/*",
      "Referer": "http://34.61.98.138:2020/lab/tree/notebooks/untitled.py",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.6 Safari/605.1.15"
    }
[E 2025-10-16 20:00:45.771 ServerApp] 500 POST /api/contents/notebooks/untitled.py/checkpoints?1760644845709 (b961125cf2e042caa8b8251d01f89643@72.33.2.45) 19.46ms referer=http://34.61.98.138:2020/lab/tree/notebooks/untitled.py
[I 2025-10-16 20:00:48.307 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 20:00:57.825 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 20:00:59.057 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-16 20:01:20.263 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 20:02:59.197 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-16 20:03:44.231 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 20:04:59.302 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-16 20:05:44.328 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 20:07:44.489 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 20:07:58.255 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 20:08:26.429 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-16 20:09:11.734 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-16 20:09:58.351 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 20:11:11.851 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-16 20:11:18.135 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 20:11:37.666 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 20:12:43.613 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 20:12:52.487 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-16 20:12:57.173 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 20:13:28.897 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 20:14:52.606 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-16 20:15:16.929 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 20:15:17.173 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 20:15:20.528 ServerApp] Starting buffering for 4339458d-8a1a-455e-abcd-5f26e4607d25:dca55064-c888-47ab-9ed4-0e711ce5fcb9
[I 2025-10-16 20:15:33.896 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 20:16:14.741 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 20:16:15.206 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 20:16:17.975 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-16 20:17:43.444 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 20:17:44.157 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-16 20:19:44.295 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-16 20:22:24.417 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 20:22:24.842 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 20:22:50.935 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 20:22:51.178 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 20:23:12.589 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-16 20:23:17.630 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-16 20:24:29.136 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 20:24:29.366 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 20:24:31.159 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-16 20:24:53.930 ServerApp] Kernel restarted: e15b07c7-4596-4a7e-9995-cc622a6d2916
[I 2025-10-16 20:24:53.958 ServerApp] Starting buffering for e15b07c7-4596-4a7e-9995-cc622a6d2916:efdce521-1011-45e0-bb78-a255e7b15746
[I 2025-10-16 20:24:54.003 ServerApp] Connecting to kernel e15b07c7-4596-4a7e-9995-cc622a6d2916.
[I 2025-10-16 20:24:54.004 ServerApp] Restoring connection for e15b07c7-4596-4a7e-9995-cc622a6d2916:efdce521-1011-45e0-bb78-a255e7b15746
[W 2025-10-16 20:24:55.374 ServerApp] Got events for closed stream <zmq.eventloop.zmqstream.ZMQStream object at 0x74ad300cde40>
[I 2025-10-16 20:25:26.246 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-16 20:27:26.440 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-16 20:29:26.617 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[W 2025-10-16 20:32:54.004 ServerApp] WebSocket ping timeout after 119846 ms.
[I 2025-10-16 20:32:59.007 ServerApp] Starting buffering for e15b07c7-4596-4a7e-9995-cc622a6d2916:efdce521-1011-45e0-bb78-a255e7b15746
[I 2025-10-16 20:44:14.225 ServerApp] 302 GET / (@162.216.149.237) 1.09ms
[I 2025-10-16 20:44:14.295 LabApp] 302 GET /lab? (@162.216.149.237) 1.31ms
[I 2025-10-16 20:46:17.866 ServerApp] Connecting to kernel e15b07c7-4596-4a7e-9995-cc622a6d2916.
[I 2025-10-16 20:46:17.866 ServerApp] Restoring connection for e15b07c7-4596-4a7e-9995-cc622a6d2916:efdce521-1011-45e0-bb78-a255e7b15746
[I 2025-10-16 20:46:34.048 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 20:46:49.567 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-16 20:46:54.928 ServerApp] Kernel restarted: e15b07c7-4596-4a7e-9995-cc622a6d2916
[I 2025-10-16 20:46:55.046 ServerApp] Starting buffering for e15b07c7-4596-4a7e-9995-cc622a6d2916:efdce521-1011-45e0-bb78-a255e7b15746
[I 2025-10-16 20:46:55.077 ServerApp] Connecting to kernel e15b07c7-4596-4a7e-9995-cc622a6d2916.
[I 2025-10-16 20:46:55.077 ServerApp] Restoring connection for e15b07c7-4596-4a7e-9995-cc622a6d2916:efdce521-1011-45e0-bb78-a255e7b15746
[I 2025-10-16 20:48:03.878 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 20:48:49.719 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-16 20:49:02.266 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 20:49:04.144 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 20:49:12.583 ServerApp] Kernel restarted: e15b07c7-4596-4a7e-9995-cc622a6d2916
[I 2025-10-16 20:49:12.672 ServerApp] Starting buffering for e15b07c7-4596-4a7e-9995-cc622a6d2916:efdce521-1011-45e0-bb78-a255e7b15746
[I 2025-10-16 20:49:12.701 ServerApp] Connecting to kernel e15b07c7-4596-4a7e-9995-cc622a6d2916.
[I 2025-10-16 20:49:12.701 ServerApp] Restoring connection for e15b07c7-4596-4a7e-9995-cc622a6d2916:efdce521-1011-45e0-bb78-a255e7b15746
[I 2025-10-16 20:49:29.715 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-16 20:51:29.826 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-16 20:51:30.458 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-16 20:52:07.280 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-16 20:52:09.915 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-16 20:54:10.027 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-16 20:56:10.150 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-16 20:58:10.263 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-16 21:00:10.376 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-16 21:02:10.486 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-16 21:02:39.194 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-16 21:04:39.332 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-16 21:06:39.455 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-16 21:08:39.573 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-16 21:10:39.759 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-16 21:18:39.994 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-16 21:20:40.113 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-16 21:22:40.230 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-16 21:24:40.346 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-16 21:25:34.235 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-16 21:27:28.241 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 21:27:34.401 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-16 21:29:28.334 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 21:29:44.595 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 21:30:41.795 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 21:32:41.893 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 21:32:43.383 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 21:34:01.859 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 21:34:19.672 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 21:35:20.590 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 21:35:23.761 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 21:35:34.514 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-16 21:35:37.370 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 21:36:09.109 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 21:36:19.181 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 21:36:43.306 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 21:36:44.720 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 21:37:01.437 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 21:37:08.077 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-16 21:37:08.289 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-16 21:37:14.073 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-16 21:37:21.326 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-16 21:37:21.557 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-16 21:37:27.458 ServerApp] Kernel restarted: e15b07c7-4596-4a7e-9995-cc622a6d2916
[I 2025-10-16 21:37:27.547 ServerApp] Starting buffering for e15b07c7-4596-4a7e-9995-cc622a6d2916:efdce521-1011-45e0-bb78-a255e7b15746
[I 2025-10-16 21:37:27.581 ServerApp] Connecting to kernel e15b07c7-4596-4a7e-9995-cc622a6d2916.
[I 2025-10-16 21:37:27.581 ServerApp] Restoring connection for e15b07c7-4596-4a7e-9995-cc622a6d2916:efdce521-1011-45e0-bb78-a255e7b15746
[I 2025-10-16 21:38:49.007 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 21:38:49.276 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 21:39:02.796 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 21:39:17.411 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 21:39:17.621 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 21:39:21.429 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-16 21:39:27.085 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 21:41:11.174 ServerApp] Saving file at /notebooks/cleaning.py
[W 2025-10-16 21:41:11.182 ServerApp] /home/kayvans/mimic-demo/notebooks/.~cleaning.py doesn't exist
[I 2025-10-16 21:41:11.474 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 21:41:21.595 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-16 21:41:54.846 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-16 21:41:56.066 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-16 21:42:11.128 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 21:43:11.281 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 21:43:56.183 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-16 21:45:11.380 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 21:45:56.334 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[W 2025-10-16 21:45:56.349 ServerApp] /home/kayvans/mimic-demo/notebooks/.~urinary_tract_infection.ipynb doesn't exist
[I 2025-10-16 21:45:59.481 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 21:47:56.447 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-16 21:53:56.570 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-16 21:53:59.581 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 21:54:37.343 ServerApp] Connecting to kernel 4339458d-8a1a-455e-abcd-5f26e4607d25.
[I 2025-10-16 21:54:59.089 ServerApp] Starting buffering for 4339458d-8a1a-455e-abcd-5f26e4607d25:0e8efda1-a6d7-4ad5-977e-888cc05b30e0
[I 2025-10-16 21:55:57.866 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-16 21:56:00.946 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 21:56:54.072 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-16 21:58:54.371 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-16 22:00:01.053 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 22:00:54.519 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-16 22:01:31.277 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 22:01:32.758 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 22:02:54.696 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-16 22:03:32.855 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 22:03:49.248 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 22:04:25.057 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 22:04:27.725 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 22:04:35.887 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 22:04:36.104 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 22:04:36.340 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 22:04:39.757 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 22:04:54.810 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-16 22:05:21.011 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 22:05:38.119 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 22:05:38.295 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 22:06:54.975 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-16 22:07:10.047 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 22:07:10.538 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 22:07:21.277 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 22:07:47.715 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 22:07:47.901 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 22:07:48.086 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 22:08:04.207 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 22:08:13.453 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 22:08:13.653 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 22:08:33.905 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 22:08:34.168 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 22:08:41.436 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 22:08:41.644 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 22:08:41.821 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 22:08:42.013 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 22:08:55.107 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-16 22:09:45.864 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 22:10:04.090 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-16 22:10:15.639 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 22:10:50.987 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 22:10:57.957 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 22:11:05.731 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-16 22:11:09.993 ServerApp] Kernel restarted: e15b07c7-4596-4a7e-9995-cc622a6d2916
[I 2025-10-16 22:11:10.016 ServerApp] Starting buffering for e15b07c7-4596-4a7e-9995-cc622a6d2916:efdce521-1011-45e0-bb78-a255e7b15746
[I 2025-10-16 22:11:10.047 ServerApp] Connecting to kernel e15b07c7-4596-4a7e-9995-cc622a6d2916.
[I 2025-10-16 22:11:10.047 ServerApp] Restoring connection for e15b07c7-4596-4a7e-9995-cc622a6d2916:efdce521-1011-45e0-bb78-a255e7b15746
[I 2025-10-16 22:11:29.282 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 22:11:44.187 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 22:11:49.087 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 22:11:50.782 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 22:12:10.211 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 22:12:12.929 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 22:12:28.515 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 22:12:48.928 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-16 22:13:10.674 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 22:14:49.041 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-16 22:21:10.782 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 22:23:10.887 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 22:23:28.183 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 22:23:41.602 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 22:23:47.750 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-16 22:25:21.985 ServerApp] AsyncIOLoopKernelRestarter: restarting kernel (1/5), keep random ports
[W 2025-10-16 22:25:21.987 ServerApp] kernel e15b07c7-4596-4a7e-9995-cc622a6d2916 restarted
[I 2025-10-16 22:25:22.047 ServerApp] Starting buffering for e15b07c7-4596-4a7e-9995-cc622a6d2916:efdce521-1011-45e0-bb78-a255e7b15746
[I 2025-10-16 22:25:22.171 ServerApp] Connecting to kernel e15b07c7-4596-4a7e-9995-cc622a6d2916.
[I 2025-10-16 22:25:22.171 ServerApp] Restoring connection for e15b07c7-4596-4a7e-9995-cc622a6d2916:efdce521-1011-45e0-bb78-a255e7b15746
[I 2025-10-16 22:25:47.902 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-16 22:26:19.897 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 22:26:20.265 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 22:27:09.459 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 22:27:10.103 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 22:27:12.935 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 22:27:15.609 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 22:27:48.025 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-16 22:28:02.536 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 22:28:02.806 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 22:29:38.696 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 22:29:48.137 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-16 22:29:51.447 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 22:29:54.472 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 22:30:18.502 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 22:30:19.337 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-16 22:30:24.081 ServerApp] Kernel restarted: e15b07c7-4596-4a7e-9995-cc622a6d2916
[I 2025-10-16 22:30:24.122 ServerApp] Starting buffering for e15b07c7-4596-4a7e-9995-cc622a6d2916:efdce521-1011-45e0-bb78-a255e7b15746
[I 2025-10-16 22:30:24.151 ServerApp] Connecting to kernel e15b07c7-4596-4a7e-9995-cc622a6d2916.
[I 2025-10-16 22:30:24.151 ServerApp] Restoring connection for e15b07c7-4596-4a7e-9995-cc622a6d2916:efdce521-1011-45e0-bb78-a255e7b15746
[I 2025-10-16 22:31:19.024 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-16 22:31:22.373 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-16 22:31:34.810 ServerApp] New terminal with automatic name: 1
[I 2025-10-16 22:32:15.613 ServerApp] Kernel shutdown: 4339458d-8a1a-455e-abcd-5f26e4607d25
[I 2025-10-16 22:32:15.621 ServerApp] Kernel shutdown: e15b07c7-4596-4a7e-9995-cc622a6d2916
[I 2025-10-16 22:32:15.630 ServerApp] EOF on FD 43; stopping reading
[I 2025-10-16 22:32:15.733 ServerApp] Terminal 1 closed
[I 2025-10-16 22:32:16.498 ServerApp] Shutting down on /api/shutdown request.
[I 2025-10-16 22:32:16.499 ServerApp] Shutting down 5 extensions

  _   _          _      _
 | | | |_ __  __| |__ _| |_ ___
 | |_| | '_ \/ _` / _` |  _/ -_)
  \___/| .__/\__,_\__,_|\__\___|
       |_|

Read the migration plan to Notebook 7 to learn about the new features and the actions to take if you are using extensions.

https://jupyter-notebook.readthedocs.io/en/latest/migrate_to_notebook7.html

Please note that updating to Notebook 7 might break some of your extensions.

[W 2025-10-24 20:15:22.716 ServerApp] ServerApp.password config is deprecated in 2.0. Use PasswordIdentityProvider.hashed_password.
[I 2025-10-24 20:15:22.815 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2025-10-24 20:15:22.821 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2025-10-24 20:15:22.826 ServerApp] jupyterlab | extension was successfully linked.
[I 2025-10-24 20:15:22.831 ServerApp] nbclassic | extension was successfully linked.
[I 2025-10-24 20:15:23.584 ServerApp] notebook_shim | extension was successfully linked.
[I 2025-10-24 20:15:23.653 ServerApp] notebook_shim | extension was successfully loaded.
[I 2025-10-24 20:15:23.656 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2025-10-24 20:15:23.657 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2025-10-24 20:15:23.669 LabApp] JupyterLab extension loaded from /home/kayvans/.local/lib/python3.10/site-packages/jupyterlab
[I 2025-10-24 20:15:23.669 LabApp] JupyterLab application directory is /home/kayvans/.local/share/jupyter/lab
[I 2025-10-24 20:15:23.670 LabApp] Extension Manager is 'pypi'.
[I 2025-10-24 20:15:23.975 ServerApp] jupyterlab | extension was successfully loaded.
[I 2025-10-24 20:15:23.989 ServerApp] nbclassic | extension was successfully loaded.
[I 2025-10-24 20:15:23.990 ServerApp] Serving notebooks from local directory: /home/kayvans/mimic-demo
[I 2025-10-24 20:15:23.990 ServerApp] Jupyter Server 2.16.0 is running at:
[I 2025-10-24 20:15:23.991 ServerApp] http://cs320:2020/lab
[I 2025-10-24 20:15:23.991 ServerApp]     http://127.0.0.1:2020/lab
[I 2025-10-24 20:15:23.991 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 2025-10-24 20:15:24.019 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-language-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
[I 2025-10-24 20:15:24.342 ServerApp] 302 GET / (@50.93.221.145) 0.80ms
[W 2025-10-24 20:15:25.066 LabApp] Could not determine jupyterlab build status without nodejs
[W 2025-10-24 20:15:25.276 ServerApp] 404 GET /api/contents/dashboard1.svg?content=0&hash=0&1761336925203 (b961125cf2e042caa8b8251d01f89643@50.93.221.145) 2.45ms referer=http://34.61.98.138:2020/lab?
[W 2025-10-24 20:15:25.276 ServerApp] 404 GET /api/contents/dashboard1.svg?content=0&hash=0&1761336925203 (50.93.221.145): No such file or directory: dashboard1.svg
[W 2025-10-24 20:15:25.278 ServerApp] 404 GET /api/contents/main.py?content=0&hash=0&1761336925203 (b961125cf2e042caa8b8251d01f89643@50.93.221.145) 1.47ms referer=http://34.61.98.138:2020/lab?
[W 2025-10-24 20:15:25.278 ServerApp] 404 GET /api/contents/main.py?content=0&hash=0&1761336925203 (50.93.221.145): No such file or directory: main.py
[W 2025-10-24 20:15:25.279 ServerApp] 404 GET /api/contents/dashboard1-query.svg?content=0&hash=0&1761336925203 (b961125cf2e042caa8b8251d01f89643@50.93.221.145) 1.87ms referer=http://34.61.98.138:2020/lab?
[W 2025-10-24 20:15:25.279 ServerApp] 404 GET /api/contents/dashboard1-query.svg?content=0&hash=0&1761336925203 (50.93.221.145): No such file or directory: dashboard1-query.svg
[W 2025-10-24 20:15:25.280 ServerApp] 404 GET /api/contents/dashboard2.svg?content=0&hash=0&1761336925203 (b961125cf2e042caa8b8251d01f89643@50.93.221.145) 2.42ms referer=http://34.61.98.138:2020/lab?
[W 2025-10-24 20:15:25.280 ServerApp] 404 GET /api/contents/dashboard2.svg?content=0&hash=0&1761336925203 (50.93.221.145): No such file or directory: dashboard2.svg
[W 2025-10-24 20:15:25.281 ServerApp] 404 GET /api/contents/index.html?content=0&hash=0&1761336925203 (b961125cf2e042caa8b8251d01f89643@50.93.221.145) 0.77ms referer=http://34.61.98.138:2020/lab?
[W 2025-10-24 20:15:25.281 ServerApp] 404 GET /api/contents/index.html?content=0&hash=0&1761336925203 (50.93.221.145): No such file or directory: index.html
[W 2025-10-24 20:15:25.305 ServerApp] 404 GET /api/contents/main.csv?content=0&hash=0&1761336925203 (b961125cf2e042caa8b8251d01f89643@50.93.221.145) 1.41ms referer=http://34.61.98.138:2020/lab?
[W 2025-10-24 20:15:25.305 ServerApp] 404 GET /api/contents/main.csv?content=0&hash=0&1761336925203 (50.93.221.145): No such file or directory: main.csv
[W 2025-10-24 20:15:25.307 ServerApp] 404 GET /api/contents/Untitled.ipynb?content=0&hash=0&1761336925203 (b961125cf2e042caa8b8251d01f89643@50.93.221.145) 1.00ms referer=http://34.61.98.138:2020/lab?
[W 2025-10-24 20:15:25.307 ServerApp] 404 GET /api/contents/Untitled.ipynb?content=0&hash=0&1761336925203 (50.93.221.145): No such file or directory: Untitled.ipynb
[W 2025-10-24 20:15:25.309 ServerApp] 404 GET /api/contents/dashboard2.svg?content=0&hash=0&1761336925203 (b961125cf2e042caa8b8251d01f89643@50.93.221.145) 1.23ms referer=http://34.61.98.138:2020/lab?
[W 2025-10-24 20:15:25.309 ServerApp] 404 GET /api/contents/dashboard2.svg?content=0&hash=0&1761336925203 (50.93.221.145): No such file or directory: dashboard2.svg
[W 2025-10-24 20:15:25.310 ServerApp] 404 GET /api/contents/README.md?content=0&hash=0&1761336925203 (b961125cf2e042caa8b8251d01f89643@50.93.221.145) 1.54ms referer=http://34.61.98.138:2020/lab?
[W 2025-10-24 20:15:25.310 ServerApp] 404 GET /api/contents/README.md?content=0&hash=0&1761336925203 (50.93.221.145): No such file or directory: README.md
[W 2025-10-24 20:15:25.311 ServerApp] 404 GET /api/contents/dashboard1-query.svg?content=0&hash=0&1761336925203 (b961125cf2e042caa8b8251d01f89643@50.93.221.145) 0.78ms referer=http://34.61.98.138:2020/lab?
[W 2025-10-24 20:15:25.311 ServerApp] 404 GET /api/contents/dashboard1-query.svg?content=0&hash=0&1761336925203 (50.93.221.145): No such file or directory: dashboard1-query.svg
[W 2025-10-24 20:15:25.312 ServerApp] 404 GET /api/contents/dashboard1.svg?content=0&hash=0&1761336925203 (b961125cf2e042caa8b8251d01f89643@50.93.221.145) 0.76ms referer=http://34.61.98.138:2020/lab?
[W 2025-10-24 20:15:25.312 ServerApp] 404 GET /api/contents/dashboard1.svg?content=0&hash=0&1761336925203 (50.93.221.145): No such file or directory: dashboard1.svg
[W 2025-10-24 20:15:25.335 ServerApp] 404 GET /api/contents/main.csv?content=0&hash=0&1761336925203 (b961125cf2e042caa8b8251d01f89643@50.93.221.145) 1.35ms referer=http://34.61.98.138:2020/lab?
[W 2025-10-24 20:15:25.335 ServerApp] 404 GET /api/contents/main.csv?content=0&hash=0&1761336925203 (50.93.221.145): No such file or directory: main.csv
[W 2025-10-24 20:15:25.337 ServerApp] 404 GET /api/contents/index.html?content=0&hash=0&1761336925203 (b961125cf2e042caa8b8251d01f89643@50.93.221.145) 1.06ms referer=http://34.61.98.138:2020/lab?
[W 2025-10-24 20:15:25.337 ServerApp] 404 GET /api/contents/index.html?content=0&hash=0&1761336925203 (50.93.221.145): No such file or directory: index.html
[W 2025-10-24 20:15:25.338 ServerApp] 404 GET /api/contents/Untitled.ipynb?content=0&hash=0&1761336925203 (b961125cf2e042caa8b8251d01f89643@50.93.221.145) 0.95ms referer=http://34.61.98.138:2020/lab?
[W 2025-10-24 20:15:25.338 ServerApp] 404 GET /api/contents/Untitled.ipynb?content=0&hash=0&1761336925203 (50.93.221.145): No such file or directory: Untitled.ipynb
[W 2025-10-24 20:15:25.341 ServerApp] 404 GET /api/contents/README.md?content=0&hash=0&1761336925203 (b961125cf2e042caa8b8251d01f89643@50.93.221.145) 1.09ms referer=http://34.61.98.138:2020/lab?
[W 2025-10-24 20:15:25.341 ServerApp] 404 GET /api/contents/README.md?content=0&hash=0&1761336925203 (50.93.221.145): No such file or directory: README.md
[W 2025-10-24 20:15:25.342 ServerApp] 404 GET /api/contents/main.csv?content=0&hash=0&1761336925204 (b961125cf2e042caa8b8251d01f89643@50.93.221.145) 1.50ms referer=http://34.61.98.138:2020/lab?
[W 2025-10-24 20:15:25.342 ServerApp] 404 GET /api/contents/main.csv?content=0&hash=0&1761336925204 (50.93.221.145): No such file or directory: main.csv
[W 2025-10-24 20:15:25.365 ServerApp] 404 GET /api/contents/main.py?content=0&hash=0&1761336925204 (b961125cf2e042caa8b8251d01f89643@50.93.221.145) 1.44ms referer=http://34.61.98.138:2020/lab?
[W 2025-10-24 20:15:25.365 ServerApp] 404 GET /api/contents/main.py?content=0&hash=0&1761336925204 (50.93.221.145): No such file or directory: main.py
[W 2025-10-24 20:15:25.367 ServerApp] 404 GET /api/contents/index.html?content=0&hash=0&1761336925204 (b961125cf2e042caa8b8251d01f89643@50.93.221.145) 0.90ms referer=http://34.61.98.138:2020/lab?
[W 2025-10-24 20:15:25.367 ServerApp] 404 GET /api/contents/index.html?content=0&hash=0&1761336925204 (50.93.221.145): No such file or directory: index.html
[I 2025-10-24 20:15:25.384 ServerApp] New terminal with automatic name: 1
[W 2025-10-24 20:15:25.476 ServerApp] The websocket_ping_timeout (90000) cannot be longer than the websocket_ping_interval (30000).
    Setting websocket_ping_timeout=30000
[I 2025-10-24 20:15:33.376 ServerApp] Kernel started: 6c82a900-907e-4d19-86e4-3734543c3532
[I 2025-10-24 20:15:34.334 ServerApp] Connecting to kernel 6c82a900-907e-4d19-86e4-3734543c3532.
[I 2025-10-24 20:15:34.338 ServerApp] Connecting to kernel 6c82a900-907e-4d19-86e4-3734543c3532.
[I 2025-10-24 20:15:34.343 ServerApp] Connecting to kernel 6c82a900-907e-4d19-86e4-3734543c3532.
[W 2025-10-24 20:15:34.433 ServerApp] Got events for closed stream <zmq.eventloop.zmqstream.ZMQStream object at 0x77c9757629e0>
[I 2025-10-24 20:17:33.358 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-24 20:17:35.062 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-24 20:19:11.654 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-24 20:19:33.637 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-24 20:20:37.197 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-24 20:20:55.599 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-24 20:21:07.423 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-24 20:21:24.218 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-24 20:22:34.301 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-24 20:22:37.126 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-24 20:23:03.708 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-24 20:23:18.939 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-24 20:23:41.402 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-24 20:25:33.765 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-24 20:25:41.512 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-24 20:26:20.802 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-24 20:26:23.259 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-24 20:26:31.310 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-24 20:26:45.755 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-24 20:26:47.356 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-24 20:27:51.850 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-24 20:28:37.005 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-24 20:28:47.504 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-24 20:28:48.818 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-24 20:28:54.527 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-24 20:30:07.434 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-24 20:30:17.922 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-24 20:30:29.020 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-24 20:30:37.043 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-24 20:32:18.118 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-24 20:33:00.294 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-24 20:33:19.239 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-24 20:35:19.362 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-24 20:36:43.536 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-24 20:36:47.496 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-24 20:38:47.624 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-24 20:40:22.484 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-24 20:41:41.094 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-24 20:42:22.619 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-24 20:43:41.428 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-24 20:45:41.740 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-24 20:47:41.949 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-24 20:49:25.794 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-24 20:49:35.136 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-24 20:50:26.306 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-24 20:52:11.864 ServerApp] Kernel restarted: 6c82a900-907e-4d19-86e4-3734543c3532
[I 2025-10-24 20:52:11.974 ServerApp] Starting buffering for 6c82a900-907e-4d19-86e4-3734543c3532:38509b85-c11f-42ed-88f7-ea4ab2e2f81e
[I 2025-10-24 20:52:12.021 ServerApp] Connecting to kernel 6c82a900-907e-4d19-86e4-3734543c3532.
[I 2025-10-24 20:52:12.021 ServerApp] Restoring connection for 6c82a900-907e-4d19-86e4-3734543c3532:38509b85-c11f-42ed-88f7-ea4ab2e2f81e
[I 2025-10-24 20:52:26.515 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-24 20:53:05.873 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-24 20:53:48.307 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-24 20:53:52.358 ServerApp] Kernel restarted: 6c82a900-907e-4d19-86e4-3734543c3532
[I 2025-10-24 20:53:52.433 ServerApp] Starting buffering for 6c82a900-907e-4d19-86e4-3734543c3532:38509b85-c11f-42ed-88f7-ea4ab2e2f81e
[I 2025-10-24 20:53:52.466 ServerApp] Connecting to kernel 6c82a900-907e-4d19-86e4-3734543c3532.
[I 2025-10-24 20:53:52.466 ServerApp] Restoring connection for 6c82a900-907e-4d19-86e4-3734543c3532:38509b85-c11f-42ed-88f7-ea4ab2e2f81e
[I 2025-10-24 20:54:11.758 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-24 20:55:16.045 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-24 20:56:10.645 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-24 20:56:30.582 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-24 20:57:03.625 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-24 20:57:11.162 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-24 20:57:28.573 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-24 20:57:31.185 ServerApp] Kernel shutdown: 6c82a900-907e-4d19-86e4-3734543c3532
[I 2025-10-24 20:57:31.206 ServerApp] EOF on FD 16; stopping reading
[I 2025-10-24 20:57:31.307 ServerApp] Terminal 1 closed
[I 2025-10-24 20:57:33.142 ServerApp] Shutting down on /api/shutdown request.
[I 2025-10-24 20:57:33.144 ServerApp] Shutting down 5 extensions

  _   _          _      _
 | | | |_ __  __| |__ _| |_ ___
 | |_| | '_ \/ _` / _` |  _/ -_)
  \___/| .__/\__,_\__,_|\__\___|
       |_|

Read the migration plan to Notebook 7 to learn about the new features and the actions to take if you are using extensions.

https://jupyter-notebook.readthedocs.io/en/latest/migrate_to_notebook7.html

Please note that updating to Notebook 7 might break some of your extensions.

[W 2025-10-25 21:26:24.330 ServerApp] ServerApp.password config is deprecated in 2.0. Use PasswordIdentityProvider.hashed_password.
[I 2025-10-25 21:26:24.425 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2025-10-25 21:26:24.430 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2025-10-25 21:26:24.436 ServerApp] jupyterlab | extension was successfully linked.
[I 2025-10-25 21:26:24.441 ServerApp] nbclassic | extension was successfully linked.
[I 2025-10-25 21:26:25.105 ServerApp] notebook_shim | extension was successfully linked.
[I 2025-10-25 21:26:25.167 ServerApp] notebook_shim | extension was successfully loaded.
[I 2025-10-25 21:26:25.170 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2025-10-25 21:26:25.171 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2025-10-25 21:26:25.180 LabApp] JupyterLab extension loaded from /home/kayvans/.local/lib/python3.10/site-packages/jupyterlab
[I 2025-10-25 21:26:25.181 LabApp] JupyterLab application directory is /home/kayvans/.local/share/jupyter/lab
[I 2025-10-25 21:26:25.181 LabApp] Extension Manager is 'pypi'.
[I 2025-10-25 21:26:25.460 ServerApp] jupyterlab | extension was successfully loaded.
[I 2025-10-25 21:26:25.473 ServerApp] nbclassic | extension was successfully loaded.
[I 2025-10-25 21:26:25.474 ServerApp] Serving notebooks from local directory: /home/kayvans/mimic-demo
[I 2025-10-25 21:26:25.474 ServerApp] Jupyter Server 2.16.0 is running at:
[I 2025-10-25 21:26:25.474 ServerApp] http://cs320:2020/lab
[I 2025-10-25 21:26:25.474 ServerApp]     http://127.0.0.1:2020/lab
[I 2025-10-25 21:26:25.474 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 2025-10-25 21:26:25.502 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-language-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
[I 2025-10-25 21:26:32.128 ServerApp] 302 GET / (@50.93.221.145) 0.76ms
[W 2025-10-25 21:26:32.679 ServerApp] 404 GET /apple-touch-icon-precomposed.png (@50.93.221.145) 25.36ms referer=None
[W 2025-10-25 21:26:32.787 ServerApp] 404 GET /apple-touch-icon.png (@50.93.221.145) 1.44ms referer=None
[W 2025-10-25 21:26:32.955 LabApp] Could not determine jupyterlab build status without nodejs
[I 2025-10-25 21:26:34.232 ServerApp] Kernel started: 7be9722b-01f1-467f-860a-6d8a52ecdfe0
[I 2025-10-25 21:26:35.030 ServerApp] Connecting to kernel 7be9722b-01f1-467f-860a-6d8a52ecdfe0.
[W 2025-10-25 21:26:35.033 ServerApp] The websocket_ping_timeout (90000) cannot be longer than the websocket_ping_interval (30000).
    Setting websocket_ping_timeout=30000
[I 2025-10-25 21:26:44.367 ServerApp] Connecting to kernel 7be9722b-01f1-467f-860a-6d8a52ecdfe0.
[I 2025-10-25 21:28:34.154 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[W 2025-10-25 21:40:05.031 ServerApp] WebSocket ping timeout after 119897 ms.
[I 2025-10-25 21:40:10.040 ServerApp] Starting buffering for 7be9722b-01f1-467f-860a-6d8a52ecdfe0:9d119d3c-6182-4eb1-ac7e-7fd72305c809
[I 2025-10-25 21:48:02.037 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-25 21:48:16.959 ServerApp] Connecting to kernel 7be9722b-01f1-467f-860a-6d8a52ecdfe0.
[I 2025-10-25 21:48:16.960 ServerApp] Restoring connection for 7be9722b-01f1-467f-860a-6d8a52ecdfe0:9d119d3c-6182-4eb1-ac7e-7fd72305c809
[I 2025-10-25 21:48:43.916 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-25 21:49:59.997 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 21:50:14.335 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 21:50:44.147 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-25 21:51:26.613 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 21:51:48.786 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 21:51:50.879 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 21:51:55.698 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 21:52:04.040 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 21:52:04.295 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 21:52:54.191 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 21:53:10.085 ServerApp] Kernel restarted: 7be9722b-01f1-467f-860a-6d8a52ecdfe0
[I 2025-10-25 21:53:10.115 ServerApp] Starting buffering for 7be9722b-01f1-467f-860a-6d8a52ecdfe0:9d119d3c-6182-4eb1-ac7e-7fd72305c809
[I 2025-10-25 21:53:10.156 ServerApp] Connecting to kernel 7be9722b-01f1-467f-860a-6d8a52ecdfe0.
[I 2025-10-25 21:53:10.156 ServerApp] Restoring connection for 7be9722b-01f1-467f-860a-6d8a52ecdfe0:9d119d3c-6182-4eb1-ac7e-7fd72305c809
[I 2025-10-25 21:54:01.464 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 21:54:14.314 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 21:54:44.463 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-25 21:54:51.501 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 21:55:08.848 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 21:55:35.802 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 21:55:42.322 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 21:55:42.721 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 21:56:44.598 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-25 21:56:44.625 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-25 21:58:16.961 ServerApp] Kernel restarted: 7be9722b-01f1-467f-860a-6d8a52ecdfe0
[I 2025-10-25 21:58:17.027 ServerApp] Starting buffering for 7be9722b-01f1-467f-860a-6d8a52ecdfe0:9d119d3c-6182-4eb1-ac7e-7fd72305c809
[I 2025-10-25 21:58:17.220 ServerApp] Connecting to kernel 7be9722b-01f1-467f-860a-6d8a52ecdfe0.
[I 2025-10-25 21:58:17.221 ServerApp] Restoring connection for 7be9722b-01f1-467f-860a-6d8a52ecdfe0:9d119d3c-6182-4eb1-ac7e-7fd72305c809
[I 2025-10-25 21:58:44.958 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-25 22:00:21.682 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 22:00:45.119 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-25 22:01:56.298 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 22:01:59.530 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 22:02:03.442 ServerApp] Kernel restarted: 7be9722b-01f1-467f-860a-6d8a52ecdfe0
[I 2025-10-25 22:02:03.540 ServerApp] Starting buffering for 7be9722b-01f1-467f-860a-6d8a52ecdfe0:9d119d3c-6182-4eb1-ac7e-7fd72305c809
[I 2025-10-25 22:02:03.572 ServerApp] Connecting to kernel 7be9722b-01f1-467f-860a-6d8a52ecdfe0.
[I 2025-10-25 22:02:03.573 ServerApp] Restoring connection for 7be9722b-01f1-467f-860a-6d8a52ecdfe0:9d119d3c-6182-4eb1-ac7e-7fd72305c809
[I 2025-10-25 22:02:45.308 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-25 22:02:46.542 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 22:03:15.854 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 22:03:16.086 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 22:03:16.660 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 22:03:25.420 ServerApp] Kernel restarted: 7be9722b-01f1-467f-860a-6d8a52ecdfe0
[I 2025-10-25 22:03:25.461 ServerApp] Starting buffering for 7be9722b-01f1-467f-860a-6d8a52ecdfe0:9d119d3c-6182-4eb1-ac7e-7fd72305c809
[I 2025-10-25 22:03:25.495 ServerApp] Connecting to kernel 7be9722b-01f1-467f-860a-6d8a52ecdfe0.
[I 2025-10-25 22:03:25.495 ServerApp] Restoring connection for 7be9722b-01f1-467f-860a-6d8a52ecdfe0:9d119d3c-6182-4eb1-ac7e-7fd72305c809
[I 2025-10-25 22:03:52.461 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 22:04:34.668 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-25 22:04:38.087 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-25 22:06:34.842 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-25 22:09:24.079 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 22:09:38.030 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 22:09:38.482 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 22:09:53.416 ServerApp] Kernel restarted: 7be9722b-01f1-467f-860a-6d8a52ecdfe0
[I 2025-10-25 22:09:53.468 ServerApp] Starting buffering for 7be9722b-01f1-467f-860a-6d8a52ecdfe0:9d119d3c-6182-4eb1-ac7e-7fd72305c809
[I 2025-10-25 22:09:53.506 ServerApp] Connecting to kernel 7be9722b-01f1-467f-860a-6d8a52ecdfe0.
[I 2025-10-25 22:09:53.506 ServerApp] Restoring connection for 7be9722b-01f1-467f-860a-6d8a52ecdfe0:9d119d3c-6182-4eb1-ac7e-7fd72305c809
[I 2025-10-25 22:10:35.271 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-25 22:10:56.333 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 22:11:05.069 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 22:12:35.629 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-25 22:13:05.351 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 22:13:27.972 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 22:13:33.877 ServerApp] Kernel restarted: 7be9722b-01f1-467f-860a-6d8a52ecdfe0
[I 2025-10-25 22:13:33.911 ServerApp] Starting buffering for 7be9722b-01f1-467f-860a-6d8a52ecdfe0:9d119d3c-6182-4eb1-ac7e-7fd72305c809
[I 2025-10-25 22:13:33.947 ServerApp] Connecting to kernel 7be9722b-01f1-467f-860a-6d8a52ecdfe0.
[I 2025-10-25 22:13:33.947 ServerApp] Restoring connection for 7be9722b-01f1-467f-860a-6d8a52ecdfe0:9d119d3c-6182-4eb1-ac7e-7fd72305c809
[I 2025-10-25 22:13:48.472 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-25 22:14:17.602 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 22:15:09.051 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 22:15:15.255 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 22:15:48.640 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-25 22:16:08.979 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 22:16:13.447 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 22:16:15.272 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 22:17:39.819 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 22:17:48.823 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-25 22:18:04.995 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 22:19:47.264 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 22:20:05.070 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 22:20:06.205 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 22:20:18.747 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 22:20:19.592 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 22:20:32.961 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 22:20:40.190 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 22:20:44.174 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 22:20:46.913 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 22:20:50.162 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 22:20:52.777 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 22:21:49.426 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-25 22:24:35.825 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 22:25:34.793 ServerApp] 302 GET / (@199.45.155.110) 1.00ms
[I 2025-10-25 22:25:47.885 ServerApp] 302 GET / (@199.45.155.110) 0.56ms
[I 2025-10-25 22:25:48.356 ServerApp] Malformed HTTP message from 199.45.155.110: Unexpected HTTP version 'HTTP/2.0'
[I 2025-10-25 22:25:49.702 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-25 22:25:56.234 LabApp] 302 GET /lab (@199.45.155.110) 1.14ms
[I 2025-10-25 22:25:56.704 ServerApp] Malformed HTTP message from 199.45.155.110: Unexpected HTTP version 'HTTP/2.0'
[I 2025-10-25 22:26:03.272 ServerApp] Malformed HTTP message from 199.45.155.110: Unexpected HTTP version 'HTTP/2.0'
[W 2025-10-25 22:26:08.355 ServerApp] 404 GET /sitemap.xml (@199.45.155.110) 2.14ms referer=None
[I 2025-10-25 22:26:35.935 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 22:27:22.921 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 22:27:24.653 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 22:28:43.125 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 22:28:45.727 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 22:28:53.733 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 22:28:54.198 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 22:29:18.506 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 22:29:34.272 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 22:29:34.728 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 22:29:40.821 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 22:29:41.510 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 22:29:49.920 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-25 22:31:10.473 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 22:31:13.725 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 22:31:46.348 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 22:31:50.191 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-25 22:33:16.222 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 22:33:25.972 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 22:33:50.402 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-25 22:34:28.111 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 22:34:39.020 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 22:35:33.920 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 22:35:45.230 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 22:35:50.575 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-25 22:35:52.699 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 22:36:11.573 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 22:36:15.583 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 22:36:16.127 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 22:36:19.548 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 22:36:31.184 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 22:36:35.815 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 22:36:36.241 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 22:36:38.594 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 22:36:44.069 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 22:37:22.830 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 22:37:27.062 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 22:37:50.733 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-25 22:39:09.074 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 22:39:17.191 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 22:39:29.984 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 22:39:50.894 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-25 22:40:07.414 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-25 22:40:25.825 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 22:40:27.940 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 22:40:36.389 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 22:41:00.377 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 22:41:11.982 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 22:41:16.234 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 22:41:51.062 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-25 22:43:16.348 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 22:51:16.466 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 22:51:22.686 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 22:51:43.284 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 22:52:03.184 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 22:52:08.907 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 22:53:11.328 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 22:53:12.948 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 22:53:27.829 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-25 22:53:37.878 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 22:53:39.644 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 22:53:42.951 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 22:55:27.986 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-25 22:56:59.476 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 22:57:28.142 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-25 22:57:40.274 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-25 22:57:46.425 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 22:57:46.784 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 22:57:55.463 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-25 22:58:32.395 ServerApp] Kernel restarted: 7be9722b-01f1-467f-860a-6d8a52ecdfe0
[I 2025-10-25 22:58:32.425 ServerApp] Starting buffering for 7be9722b-01f1-467f-860a-6d8a52ecdfe0:9d119d3c-6182-4eb1-ac7e-7fd72305c809
[I 2025-10-25 22:58:32.461 ServerApp] Connecting to kernel 7be9722b-01f1-467f-860a-6d8a52ecdfe0.
[I 2025-10-25 22:58:32.462 ServerApp] Restoring connection for 7be9722b-01f1-467f-860a-6d8a52ecdfe0:9d119d3c-6182-4eb1-ac7e-7fd72305c809
[I 2025-10-25 22:59:17.774 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-25 23:00:37.325 ServerApp] Kernel shutdown: 7be9722b-01f1-467f-860a-6d8a52ecdfe0
[I 2025-10-25 23:00:37.981 ServerApp] Shutting down on /api/shutdown request.
[I 2025-10-25 23:00:37.982 ServerApp] Shutting down 5 extensions

  _   _          _      _
 | | | |_ __  __| |__ _| |_ ___
 | |_| | '_ \/ _` / _` |  _/ -_)
  \___/| .__/\__,_\__,_|\__\___|
       |_|

Read the migration plan to Notebook 7 to learn about the new features and the actions to take if you are using extensions.

https://jupyter-notebook.readthedocs.io/en/latest/migrate_to_notebook7.html

Please note that updating to Notebook 7 might break some of your extensions.

[W 2025-10-28 02:19:17.129 ServerApp] ServerApp.password config is deprecated in 2.0. Use PasswordIdentityProvider.hashed_password.
[I 2025-10-28 02:19:17.222 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2025-10-28 02:19:17.227 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2025-10-28 02:19:17.233 ServerApp] jupyterlab | extension was successfully linked.
[I 2025-10-28 02:19:17.238 ServerApp] nbclassic | extension was successfully linked.
[I 2025-10-28 02:19:17.889 ServerApp] notebook_shim | extension was successfully linked.
[I 2025-10-28 02:19:17.952 ServerApp] notebook_shim | extension was successfully loaded.
[I 2025-10-28 02:19:17.955 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2025-10-28 02:19:17.956 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2025-10-28 02:19:17.966 LabApp] JupyterLab extension loaded from /home/kayvans/.local/lib/python3.10/site-packages/jupyterlab
[I 2025-10-28 02:19:17.966 LabApp] JupyterLab application directory is /home/kayvans/.local/share/jupyter/lab
[I 2025-10-28 02:19:17.967 LabApp] Extension Manager is 'pypi'.
[I 2025-10-28 02:19:18.256 ServerApp] jupyterlab | extension was successfully loaded.
[I 2025-10-28 02:19:18.270 ServerApp] nbclassic | extension was successfully loaded.
[I 2025-10-28 02:19:18.271 ServerApp] Serving notebooks from local directory: /home/kayvans/mimic-demo
[I 2025-10-28 02:19:18.271 ServerApp] Jupyter Server 2.16.0 is running at:
[I 2025-10-28 02:19:18.271 ServerApp] http://cs320:2020/lab
[I 2025-10-28 02:19:18.271 ServerApp]     http://127.0.0.1:2020/lab
[I 2025-10-28 02:19:18.271 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 2025-10-28 02:19:18.300 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-language-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
[I 2025-10-28 02:19:19.687 ServerApp] 302 GET / (@50.93.221.145) 0.81ms
[W 2025-10-28 02:19:20.548 LabApp] Could not determine jupyterlab build status without nodejs
[W 2025-10-28 02:19:20.768 ServerApp] 404 GET /api/contents/cleaning.py?content=0&hash=0&1761617960706 (b961125cf2e042caa8b8251d01f89643@50.93.221.145) 1.70ms referer=http://34.61.98.138:2020/lab?
[W 2025-10-28 02:19:20.768 ServerApp] 404 GET /api/contents/cleaning.py?content=0&hash=0&1761617960706 (50.93.221.145): No such file or directory: cleaning.py
[W 2025-10-28 02:19:20.769 ServerApp] 404 GET /api/contents/urinary_tract_infection.ipynb?content=0&hash=0&1761617960706 (b961125cf2e042caa8b8251d01f89643@50.93.221.145) 2.25ms referer=http://34.61.98.138:2020/lab?
[W 2025-10-28 02:19:20.769 ServerApp] 404 GET /api/contents/urinary_tract_infection.ipynb?content=0&hash=0&1761617960706 (50.93.221.145): No such file or directory: urinary_tract_infection.ipynb
[W 2025-10-28 02:19:20.771 ServerApp] 404 GET /api/contents/cleaning.py?content=0&hash=0&1761617960707 (b961125cf2e042caa8b8251d01f89643@50.93.221.145) 1.32ms referer=http://34.61.98.138:2020/lab?
[W 2025-10-28 02:19:20.771 ServerApp] 404 GET /api/contents/cleaning.py?content=0&hash=0&1761617960707 (50.93.221.145): No such file or directory: cleaning.py
[W 2025-10-28 02:19:20.771 ServerApp] 404 GET /api/contents/urinary_tract_infection.ipynb?content=0&hash=0&1761617960707 (b961125cf2e042caa8b8251d01f89643@50.93.221.145) 1.63ms referer=http://34.61.98.138:2020/lab?
[W 2025-10-28 02:19:20.771 ServerApp] 404 GET /api/contents/urinary_tract_infection.ipynb?content=0&hash=0&1761617960707 (50.93.221.145): No such file or directory: urinary_tract_infection.ipynb
[I 2025-10-28 02:33:13.825 ServerApp] Kernel started: 2528efd3-edac-446a-bf3a-b5e69da74515
[I 2025-10-28 02:33:14.932 ServerApp] Connecting to kernel 2528efd3-edac-446a-bf3a-b5e69da74515.
[I 2025-10-28 02:33:14.937 ServerApp] Connecting to kernel 2528efd3-edac-446a-bf3a-b5e69da74515.
[I 2025-10-28 02:33:14.942 ServerApp] Connecting to kernel 2528efd3-edac-446a-bf3a-b5e69da74515.
[W 2025-10-28 02:33:14.946 ServerApp] The websocket_ping_timeout (90000) cannot be longer than the websocket_ping_interval (30000).
    Setting websocket_ping_timeout=30000
[I 2025-10-28 02:41:14.046 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-28 02:41:36.184 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-28 02:43:36.412 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-28 02:45:14.810 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-28 02:45:36.544 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-28 02:47:15.018 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-28 02:47:36.816 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-28 02:49:36.965 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-28 02:51:37.099 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-28 02:52:45.478 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-28 02:53:37.336 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-28 02:54:45.643 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-28 02:55:04.889 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-28 03:03:44.135 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-28 03:03:45.198 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-28 03:05:38.004 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-28 03:05:45.488 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-28 03:07:19.609 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-28 03:07:20.381 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-28 03:07:38.186 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-28 03:08:07.203 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-28 03:09:57.549 ServerApp] 302 GET / (@50.93.221.145) 0.92ms
[W 2025-10-28 03:09:58.896 LabApp] Could not determine jupyterlab build status without nodejs
[I 2025-10-28 03:09:58.946 ServerApp] Connecting to kernel 2528efd3-edac-446a-bf3a-b5e69da74515.
[I 2025-10-28 03:10:07.629 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-28 03:14:07.854 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-28 03:14:38.151 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-28 03:16:08.166 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-28 03:20:38.436 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-28 03:22:38.555 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-28 03:24:18.953 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-28 03:24:22.127 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-28 03:24:42.917 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-28 03:24:49.755 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-28 03:25:42.688 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-28 03:25:46.837 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-28 03:25:47.222 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-28 03:26:08.552 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-28 03:26:14.914 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-28 03:26:28.780 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-28 03:26:35.758 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-28 03:26:53.942 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-28 03:27:36.835 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-28 03:27:40.093 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-28 03:28:19.586 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-28 03:29:40.882 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-28 03:30:10.601 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-28 03:31:04.137 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-28 03:31:41.129 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-28 03:32:27.066 ServerApp] Kernel restarted: 2528efd3-edac-446a-bf3a-b5e69da74515
[I 2025-10-28 03:32:27.156 ServerApp] Starting buffering for 2528efd3-edac-446a-bf3a-b5e69da74515:dc7e66db-6d7f-4741-8323-f7ddd7f60639
[I 2025-10-28 03:32:27.190 ServerApp] Connecting to kernel 2528efd3-edac-446a-bf3a-b5e69da74515.
[I 2025-10-28 03:32:27.190 ServerApp] Restoring connection for 2528efd3-edac-446a-bf3a-b5e69da74515:dc7e66db-6d7f-4741-8323-f7ddd7f60639
[I 2025-10-28 03:33:28.723 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-28 03:33:32.885 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-28 03:34:17.278 ServerApp] Kernel restarted: 2528efd3-edac-446a-bf3a-b5e69da74515
[I 2025-10-28 03:34:17.451 ServerApp] Starting buffering for 2528efd3-edac-446a-bf3a-b5e69da74515:dc7e66db-6d7f-4741-8323-f7ddd7f60639
[I 2025-10-28 03:34:17.484 ServerApp] Connecting to kernel 2528efd3-edac-446a-bf3a-b5e69da74515.
[I 2025-10-28 03:34:17.484 ServerApp] Restoring connection for 2528efd3-edac-446a-bf3a-b5e69da74515:dc7e66db-6d7f-4741-8323-f7ddd7f60639
[I 2025-10-28 03:35:05.631 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-28 03:37:36.281 ServerApp] Starting buffering for 2528efd3-edac-446a-bf3a-b5e69da74515:dc7e66db-6d7f-4741-8323-f7ddd7f60639
[I 2025-10-28 03:37:40.546 ServerApp] Kernel shutdown: 2528efd3-edac-446a-bf3a-b5e69da74515
[I 2025-10-28 03:37:41.150 ServerApp] Shutting down on /api/shutdown request.
[I 2025-10-28 03:37:41.152 ServerApp] Shutting down 5 extensions

  _   _          _      _
 | | | |_ __  __| |__ _| |_ ___
 | |_| | '_ \/ _` / _` |  _/ -_)
  \___/| .__/\__,_\__,_|\__\___|
       |_|

Read the migration plan to Notebook 7 to learn about the new features and the actions to take if you are using extensions.

https://jupyter-notebook.readthedocs.io/en/latest/migrate_to_notebook7.html

Please note that updating to Notebook 7 might break some of your extensions.

[W 2025-10-28 23:33:11.213 ServerApp] ServerApp.password config is deprecated in 2.0. Use PasswordIdentityProvider.hashed_password.
[I 2025-10-28 23:33:11.316 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2025-10-28 23:33:11.321 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2025-10-28 23:33:11.327 ServerApp] jupyterlab | extension was successfully linked.
[I 2025-10-28 23:33:11.332 ServerApp] nbclassic | extension was successfully linked.
[I 2025-10-28 23:33:12.014 ServerApp] notebook_shim | extension was successfully linked.
[I 2025-10-28 23:33:12.080 ServerApp] notebook_shim | extension was successfully loaded.
[I 2025-10-28 23:33:12.084 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2025-10-28 23:33:12.085 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2025-10-28 23:33:12.096 LabApp] JupyterLab extension loaded from /home/kayvans/.local/lib/python3.10/site-packages/jupyterlab
[I 2025-10-28 23:33:12.096 LabApp] JupyterLab application directory is /home/kayvans/.local/share/jupyter/lab
[I 2025-10-28 23:33:12.097 LabApp] Extension Manager is 'pypi'.
[I 2025-10-28 23:33:12.395 ServerApp] jupyterlab | extension was successfully loaded.
[I 2025-10-28 23:33:12.409 ServerApp] nbclassic | extension was successfully loaded.
[I 2025-10-28 23:33:12.410 ServerApp] Serving notebooks from local directory: /home/kayvans/mimic-demo
[I 2025-10-28 23:33:12.410 ServerApp] Jupyter Server 2.16.0 is running at:
[I 2025-10-28 23:33:12.410 ServerApp] http://cs320:2020/lab
[I 2025-10-28 23:33:12.410 ServerApp]     http://127.0.0.1:2020/lab
[I 2025-10-28 23:33:12.411 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 2025-10-28 23:33:12.439 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-language-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
[I 2025-10-28 23:33:16.634 ServerApp] 302 GET / (@72.33.2.84) 0.67ms
[W 2025-10-28 23:33:17.837 LabApp] Could not determine jupyterlab build status without nodejs
[I 2025-10-28 23:33:24.116 ServerApp] Kernel started: 499ea461-9399-45a5-a394-c07e25686293
[I 2025-10-28 23:33:25.035 ServerApp] Connecting to kernel 499ea461-9399-45a5-a394-c07e25686293.
[I 2025-10-28 23:33:25.040 ServerApp] Connecting to kernel 499ea461-9399-45a5-a394-c07e25686293.
[I 2025-10-28 23:33:25.045 ServerApp] Connecting to kernel 499ea461-9399-45a5-a394-c07e25686293.
[W 2025-10-28 23:33:25.049 ServerApp] The websocket_ping_timeout (90000) cannot be longer than the websocket_ping_interval (30000).
    Setting websocket_ping_timeout=30000
[I 2025-10-28 23:35:24.002 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-28 23:39:24.263 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-28 23:41:24.379 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-28 23:41:46.848 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-28 23:43:22.657 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-28 23:43:46.979 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-28 23:44:36.022 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-28 23:45:52.187 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-28 23:47:52.305 ServerApp] Saving file at /notebooks/cleaning.py
[W 2025-10-28 23:59:55.043 ServerApp] WebSocket ping timeout after 119805 ms.
[I 2025-10-29 00:00:00.048 ServerApp] Starting buffering for 499ea461-9399-45a5-a394-c07e25686293:0fc22054-ecd9-4c94-9a98-c72396177bee
[I 2025-10-29 00:21:44.684 ServerApp] Connecting to kernel 499ea461-9399-45a5-a394-c07e25686293.
[I 2025-10-29 00:21:44.684 ServerApp] Restoring connection for 499ea461-9399-45a5-a394-c07e25686293:0fc22054-ecd9-4c94-9a98-c72396177bee
[I 2025-10-29 00:27:02.183 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-29 00:27:26.876 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-29 00:27:33.737 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-29 00:27:52.508 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-29 00:28:55.566 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-29 00:29:04.030 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-29 00:29:12.648 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-29 00:29:52.618 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-29 00:31:12.843 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-29 00:31:52.819 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-29 00:32:14.326 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-29 00:33:52.932 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-29 00:34:14.494 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-29 00:34:35.154 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-29 00:34:38.480 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-29 00:34:49.131 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-29 00:35:43.285 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-29 00:35:53.166 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-29 00:37:43.557 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-29 00:43:41.394 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-29 00:43:44.136 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-29 00:43:44.976 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-29 00:43:54.239 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-29 00:43:57.718 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-29 00:44:33.013 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-29 00:44:45.383 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-29 00:45:53.315 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-29 00:46:35.886 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-29 00:47:01.983 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-29 00:47:05.379 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-29 00:47:53.539 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-29 00:48:37.167 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-29 00:48:45.656 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-29 00:48:49.240 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-29 00:49:05.946 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-29 00:49:27.392 ServerApp] 302 GET / (@199.45.155.66) 0.96ms
[I 2025-10-29 00:49:40.791 ServerApp] 302 GET / (@199.45.155.66) 0.61ms
[I 2025-10-29 00:49:42.784 ServerApp] Malformed HTTP message from 199.45.155.66: Unexpected HTTP version 'HTTP/2.0'
[I 2025-10-29 00:49:52.572 LabApp] 302 GET /lab (@199.45.155.66) 1.10ms
[I 2025-10-29 00:49:53.650 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-29 00:49:55.021 ServerApp] Malformed HTTP message from 199.45.155.66: Unexpected HTTP version 'HTTP/2.0'
[I 2025-10-29 00:50:22.603 ServerApp] Malformed HTTP message from 199.45.155.66: Unexpected HTTP version 'HTTP/2.0'
[W 2025-10-29 00:50:36.969 ServerApp] 404 GET /wiki (@199.45.155.66) 8.98ms referer=None
[I 2025-10-29 00:58:53.528 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-29 00:59:53.784 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[W 2025-10-29 01:04:14.687 ServerApp] WebSocket ping timeout after 119867 ms.
[I 2025-10-29 01:04:19.691 ServerApp] Starting buffering for 499ea461-9399-45a5-a394-c07e25686293:0fc22054-ecd9-4c94-9a98-c72396177bee
[I 2025-10-29 01:13:55.581 ServerApp] Connecting to kernel 499ea461-9399-45a5-a394-c07e25686293.
[I 2025-10-29 01:13:55.581 ServerApp] Restoring connection for 499ea461-9399-45a5-a394-c07e25686293:0fc22054-ecd9-4c94-9a98-c72396177bee
[W 2025-10-29 01:15:25.584 ServerApp] WebSocket ping timeout after 90002 ms.
[I 2025-10-29 01:15:30.586 ServerApp] Starting buffering for 499ea461-9399-45a5-a394-c07e25686293:0fc22054-ecd9-4c94-9a98-c72396177bee
[I 2025-10-29 01:17:07.085 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-29 01:18:55.880 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-29 01:18:56.995 ServerApp] Connecting to kernel 499ea461-9399-45a5-a394-c07e25686293.
[I 2025-10-29 01:18:56.995 ServerApp] Restoring connection for 499ea461-9399-45a5-a394-c07e25686293:0fc22054-ecd9-4c94-9a98-c72396177bee
[I 2025-10-29 01:19:02.597 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-29 01:19:05.305 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-29 01:19:05.655 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-29 01:19:06.061 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-29 01:19:07.422 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-29 01:19:07.705 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-29 01:19:09.030 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-29 01:19:09.362 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-29 01:21:02.866 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-29 01:23:03.069 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-29 01:24:54.944 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-29 01:26:55.152 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-29 01:28:32.597 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-29 01:29:05.994 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-29 01:29:11.636 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-29 01:29:29.048 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-29 01:29:31.497 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-29 01:29:32.111 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-29 01:29:34.006 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-29 01:29:35.361 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-29 01:29:36.385 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-29 01:29:40.901 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-29 01:29:42.915 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-29 01:29:43.556 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-29 01:29:44.019 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-29 01:29:44.394 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-29 01:29:50.940 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-29 01:31:38.662 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-29 01:31:40.683 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-29 01:31:51.075 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-29 01:32:03.224 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-29 01:32:56.042 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-29 01:33:01.906 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-29 01:33:03.321 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-29 01:37:26.628 ServerApp] Kernel shutdown: 499ea461-9399-45a5-a394-c07e25686293
[I 2025-10-29 01:37:28.020 ServerApp] Shutting down on /api/shutdown request.
[I 2025-10-29 01:37:28.022 ServerApp] Shutting down 5 extensions

  _   _          _      _
 | | | |_ __  __| |__ _| |_ ___
 | |_| | '_ \/ _` / _` |  _/ -_)
  \___/| .__/\__,_\__,_|\__\___|
       |_|

Read the migration plan to Notebook 7 to learn about the new features and the actions to take if you are using extensions.

https://jupyter-notebook.readthedocs.io/en/latest/migrate_to_notebook7.html

Please note that updating to Notebook 7 might break some of your extensions.

[W 2025-10-30 00:02:45.349 ServerApp] ServerApp.password config is deprecated in 2.0. Use PasswordIdentityProvider.hashed_password.
[I 2025-10-30 00:02:45.445 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2025-10-30 00:02:45.451 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2025-10-30 00:02:45.457 ServerApp] jupyterlab | extension was successfully linked.
[I 2025-10-30 00:02:45.462 ServerApp] nbclassic | extension was successfully linked.
[I 2025-10-30 00:02:46.190 ServerApp] notebook_shim | extension was successfully linked.
[I 2025-10-30 00:02:46.255 ServerApp] notebook_shim | extension was successfully loaded.
[I 2025-10-30 00:02:46.258 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2025-10-30 00:02:46.259 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2025-10-30 00:02:46.270 LabApp] JupyterLab extension loaded from /home/kayvans/.local/lib/python3.10/site-packages/jupyterlab
[I 2025-10-30 00:02:46.270 LabApp] JupyterLab application directory is /home/kayvans/.local/share/jupyter/lab
[I 2025-10-30 00:02:46.271 LabApp] Extension Manager is 'pypi'.
[I 2025-10-30 00:02:46.570 ServerApp] jupyterlab | extension was successfully loaded.
[I 2025-10-30 00:02:46.584 ServerApp] nbclassic | extension was successfully loaded.
[I 2025-10-30 00:02:46.585 ServerApp] Serving notebooks from local directory: /home/kayvans/mimic-demo
[I 2025-10-30 00:02:46.585 ServerApp] Jupyter Server 2.16.0 is running at:
[I 2025-10-30 00:02:46.585 ServerApp] http://cs320:2020/lab
[I 2025-10-30 00:02:46.585 ServerApp]     http://127.0.0.1:2020/lab
[I 2025-10-30 00:02:46.585 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 2025-10-30 00:02:46.619 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-language-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
[I 2025-10-30 00:02:49.257 ServerApp] 302 GET / (@50.93.221.145) 0.62ms
[W 2025-10-30 00:02:49.777 ServerApp] 404 GET /apple-touch-icon-precomposed.png (@50.93.221.145) 33.02ms referer=None
[W 2025-10-30 00:02:49.885 ServerApp] 404 GET /apple-touch-icon.png (@50.93.221.145) 1.39ms referer=None
[W 2025-10-30 00:02:50.022 LabApp] Could not determine jupyterlab build status without nodejs
[I 2025-10-30 00:02:51.220 ServerApp] Kernel started: bf42b962-0aa8-4b4b-ba01-68a85064678c
[I 2025-10-30 00:02:52.228 ServerApp] Connecting to kernel bf42b962-0aa8-4b4b-ba01-68a85064678c.
[W 2025-10-30 00:02:52.232 ServerApp] The websocket_ping_timeout (90000) cannot be longer than the websocket_ping_interval (30000).
    Setting websocket_ping_timeout=30000
[I 2025-10-30 00:03:41.746 ServerApp] Connecting to kernel bf42b962-0aa8-4b4b-ba01-68a85064678c.
[I 2025-10-30 00:10:51.259 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-30 00:10:51.289 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-30 00:11:16.653 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-30 00:11:22.805 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-30 00:11:32.134 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-30 00:12:51.526 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-30 00:13:13.708 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-30 00:13:23.499 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-30 00:14:37.912 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-30 00:15:13.941 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-30 00:20:38.133 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-30 00:21:14.162 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-30 00:22:57.795 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-30 00:24:27.715 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
Task exception was never retrieved
future: <Task finished name='Task-2689' coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py:1111> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1113, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1115, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Task exception was never retrieved
future: <Task finished name='Task-2697' coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py:1111> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1113, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1115, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Task exception was never retrieved
future: <Task finished name='Task-2699' coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py:1111> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1113, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1115, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Task exception was never retrieved
future: <Task finished name='Task-2701' coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py:1111> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1113, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1115, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Task exception was never retrieved
future: <Task finished name='Task-2704' coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py:1111> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1113, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1115, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Task exception was never retrieved
future: <Task finished name='Task-2705' coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py:1111> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1113, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1115, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Task exception was never retrieved
future: <Task finished name='Task-2716' coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py:1111> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1113, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1115, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Task exception was never retrieved
future: <Task finished name='Task-2718' coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py:1111> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1113, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1115, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Task exception was never retrieved
future: <Task finished name='Task-2720' coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py:1111> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1113, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1115, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Task exception was never retrieved
future: <Task finished name='Task-2723' coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py:1111> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1113, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1115, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Task exception was never retrieved
future: <Task finished name='Task-2724' coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py:1111> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1113, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1115, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Task exception was never retrieved
future: <Task finished name='Task-2734' coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py:1111> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1113, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1115, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Task exception was never retrieved
future: <Task finished name='Task-2736' coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py:1111> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1113, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1115, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Task exception was never retrieved
future: <Task finished name='Task-2738' coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py:1111> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1113, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1115, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Task exception was never retrieved
future: <Task finished name='Task-2741' coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py:1111> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1113, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1115, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Task exception was never retrieved
future: <Task finished name='Task-2742' coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py:1111> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1113, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1115, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Task exception was never retrieved
future: <Task finished name='Task-2753' coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py:1111> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1113, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1115, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Task exception was never retrieved
future: <Task finished name='Task-2755' coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py:1111> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1113, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1115, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Task exception was never retrieved
future: <Task finished name='Task-2757' coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py:1111> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1113, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1115, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Task exception was never retrieved
future: <Task finished name='Task-2760' coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py:1111> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1113, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1115, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Task exception was never retrieved
future: <Task finished name='Task-2761' coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py:1111> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1113, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1115, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Task exception was never retrieved
future: <Task finished name='Task-2772' coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py:1111> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1113, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1115, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Task exception was never retrieved
future: <Task finished name='Task-2774' coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py:1111> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1113, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1115, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Task exception was never retrieved
future: <Task finished name='Task-2776' coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py:1111> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1113, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1115, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Task exception was never retrieved
future: <Task finished name='Task-2779' coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py:1111> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1113, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1115, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Task exception was never retrieved
future: <Task finished name='Task-2780' coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py:1111> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1113, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1115, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Task exception was never retrieved
future: <Task finished name='Task-2793' coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py:1111> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1113, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1115, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Task exception was never retrieved
future: <Task finished name='Task-2795' coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py:1111> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1113, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1115, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Task exception was never retrieved
future: <Task finished name='Task-2797' coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py:1111> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1113, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1115, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Task exception was never retrieved
future: <Task finished name='Task-2800' coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py:1111> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1113, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1115, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Task exception was never retrieved
future: <Task finished name='Task-2801' coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py:1111> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1113, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1115, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Task exception was never retrieved
future: <Task finished name='Task-2813' coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py:1111> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1113, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1115, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Task exception was never retrieved
future: <Task finished name='Task-2815' coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py:1111> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1113, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1115, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Task exception was never retrieved
future: <Task finished name='Task-2817' coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py:1111> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1113, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1115, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Task exception was never retrieved
future: <Task finished name='Task-2820' coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py:1111> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1113, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1115, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Task exception was never retrieved
future: <Task finished name='Task-2821' coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py:1111> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1113, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1115, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Task exception was never retrieved
future: <Task finished name='Task-2845' coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py:1111> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1113, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1115, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Task exception was never retrieved
future: <Task finished name='Task-2847' coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py:1111> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1113, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1115, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Task exception was never retrieved
future: <Task finished name='Task-2849' coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py:1111> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1113, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1115, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Task exception was never retrieved
future: <Task finished name='Task-2852' coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py:1111> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1113, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1115, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Task exception was never retrieved
future: <Task finished name='Task-2853' coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py:1111> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1113, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1115, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Task exception was never retrieved
future: <Task finished name='Task-2867' coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py:1111> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1113, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1115, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Task exception was never retrieved
future: <Task finished name='Task-2869' coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py:1111> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1113, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1115, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Task exception was never retrieved
future: <Task finished name='Task-2871' coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py:1111> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1113, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1115, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Task exception was never retrieved
future: <Task finished name='Task-2874' coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py:1111> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1113, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1115, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Task exception was never retrieved
future: <Task finished name='Task-2875' coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py:1111> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1113, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1115, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Task exception was never retrieved
future: <Task finished name='Task-2899' coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py:1111> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1113, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1115, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Task exception was never retrieved
future: <Task finished name='Task-2901' coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py:1111> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1113, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1115, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Task exception was never retrieved
future: <Task finished name='Task-2903' coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py:1111> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1113, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1115, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Task exception was never retrieved
future: <Task finished name='Task-2906' coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py:1111> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1113, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1115, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Task exception was never retrieved
future: <Task finished name='Task-2907' coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py:1111> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1113, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1115, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Task exception was never retrieved
future: <Task finished name='Task-2919' coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py:1111> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1113, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1115, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Task exception was never retrieved
future: <Task finished name='Task-2921' coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py:1111> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1113, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1115, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Task exception was never retrieved
future: <Task finished name='Task-2923' coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py:1111> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1113, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1115, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Task exception was never retrieved
future: <Task finished name='Task-2926' coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py:1111> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1113, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1115, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Task exception was never retrieved
future: <Task finished name='Task-2927' coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py:1111> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1113, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1115, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Task exception was never retrieved
future: <Task finished name='Task-2954' coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py:1111> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1113, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1115, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Task exception was never retrieved
future: <Task finished name='Task-2956' coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py:1111> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1113, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1115, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Task exception was never retrieved
future: <Task finished name='Task-2958' coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py:1111> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1113, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1115, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Task exception was never retrieved
future: <Task finished name='Task-2961' coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py:1111> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1113, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1115, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Task exception was never retrieved
future: <Task finished name='Task-2962' coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py:1111> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1113, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kayvans/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1115, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
[I 2025-10-30 00:26:27.913 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-30 00:26:38.258 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-30 00:28:28.210 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-30 00:29:55.532 ServerApp] 302 GET / (@162.142.125.113) 0.80ms
[I 2025-10-30 00:29:55.716 ServerApp] Malformed HTTP message from 162.142.125.113: Unexpected HTTP version 'HTTP/2.0'
[I 2025-10-30 00:30:01.199 LabApp] 302 GET /lab (@162.142.125.113) 1.10ms
[I 2025-10-30 00:30:01.961 ServerApp] Malformed HTTP message from 162.142.125.113: Unexpected HTTP version 'HTTP/2.0'
[I 2025-10-30 00:30:14.341 ServerApp] Malformed HTTP message from 162.142.125.113: Unexpected HTTP version 'HTTP/2.0'
[W 2025-10-30 00:30:20.801 ServerApp] 404 GET /security.txt (@162.142.125.113) 2.06ms referer=None
[I 2025-10-30 00:30:28.470 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-30 00:32:13.448 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-30 00:32:45.820 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-30 00:34:46.055 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-30 00:36:46.264 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-30 00:37:06.841 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-30 00:39:07.120 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-30 00:41:07.351 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-30 00:43:07.673 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-30 00:45:07.971 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-30 00:47:08.114 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-30 00:48:05.856 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-30 00:49:27.385 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-30 00:50:05.986 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-30 00:51:27.637 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-30 00:52:06.141 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-30 00:53:12.858 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-30 00:54:57.935 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-30 00:55:15.893 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-30 00:55:25.239 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-30 00:56:06.395 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-30 00:57:25.419 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-30 00:59:25.677 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-30 01:00:05.964 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-30 01:00:47.103 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-30 01:00:51.461 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-30 01:01:10.489 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-30 01:01:17.816 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-30 01:02:06.880 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-30 01:02:20.771 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-30 01:07:24.133 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-30 01:08:32.711 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-30 01:08:59.663 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-30 01:09:03.065 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-30 01:09:14.649 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-30 01:09:17.012 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-30 01:09:17.305 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-30 01:09:38.075 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-30 01:09:39.543 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-30 01:09:39.843 ServerApp] Saving file at /notebooks/cleaning.py
[I 2025-10-30 01:10:07.220 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-30 01:12:03.662 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-30 01:12:23.065 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-30 01:13:35.819 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-30 01:15:36.002 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[I 2025-10-30 01:19:29.307 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
[W 2025-10-30 01:19:46.105 ServerApp] delete /csv_files/draft1.csv
[I 2025-10-30 01:19:48.587 ServerApp] Saving file at /notebooks/urinary_tract_infection.ipynb
